#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test spring-boot services
          caches:
            - maven
          script:
            - mvn -B clean package --file pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.2.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Build and test angular webapp
          image: node:10.15.0
          script:
            - apt-get update && apt-get install -yq libgconf-2-4
            - >
              apt-get update && apt-get install -y wget --no-install-recommends && \
                           wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  && \
                           sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
                           apt-get update && \
                           apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
            - cd webui
            - npm install
            - npm run test:prod
            - npm run build
          artifacts:
            - dist/**
